### ISSUE TITLE
执行检索后有1125MiB的GPU占用，在哪里能设置GPU占用大小或者不占用

### ISSUE THREAD

**Issue by xiaoguo1992** [iMagist486/ElasticSearch-Langchain-Chatglm2#11]
我在您代码上做了一些更改，大致是将自己的数据写入es，写入了metadata，发现除了模型本身占用显存，还有执行查询后，显存出现占用的情况，请问这个在哪里设置？是ES的设置还是langtchain的设置？不太懂原理
![查询语句](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/73973571/4f425ce7-61fc-4749-8d53-5dcfb35de2cb)
![显存占用](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/73973571/f73e8096-e381-4ec8-aae9-828292702c6a)

**Comment by iMagist486** [comment]
你这个情况我没遇到过，可以逐步debug看看，项目里涉及到显存占用的只有embedding模型和LLM

**Comment by xiaoguo1992** [comment]
感谢您的回复，按照您说的思路，我找到embedding.py,修改了默认设置，现在不占用显存了
![embedding占用显存](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/73973571/0401fccc-aeb2-43ab-a322-0606638f646f)
