### ISSUE TITLE
知识库文档类型的问题

### ISSUE THREAD

**Issue by tomdog163** [iMagist486/ElasticSearch-Langchain-Chatglm2#4]
我试了一下可以上传.md和.txt的文件，但是.docx和.pdf文件上传有错误。大佬这个问题怎么可以修复一下？

**Comment by iMagist486** [comment]
docx文件也是可以的，报错应该是因为编码问题，你尝试重新保存下文件使用utf-8编码。 pdf暂时不支持，你可以参考[langchain-ChatGLM](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/textsplitter/chinese_text_splitter.py) 进行替换
