### ISSUE TITLE
想问一下机器配置

### ISSUE THREAD

**Issue by huaizhe2012** [iMagist486/ElasticSearch-Langchain-Chatglm2#7]
您好，学生党，想问一下最低什么配置可以让这个项目跑起来，对GPU的要求这些，谢谢您

**Comment by iMagist486** [comment]
这个主要取决于你使用的模型，量化后的模型对显存要求低一些，INT4量化级别下最低只需6GB显存。我用的是没有量化过的ChatGLM2-6b，16G显存可以跑起来。
