### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by winnie1228** [iMagist486/ElasticSearch-Langchain-Chatglm2#8]
![image](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/78136057/92d16d8c-fafe-481a-9525-8cb1f30b7cb7)
请问这个错误是什么情况？

**Comment by iMagist486** [comment]
ES配置的问题，你配置好ES后用ping（）方法看一下通不通

**Comment by iMagist486** [comment]
https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/blob/d44e149a70d10d627ecb6cd39c211fa0c1a73da4/utils/es_tool.py#L1-L17C1

**Comment by winnie1228** [comment]
> ES配置的问题，你配置好ES后用ping（）方法看一下通不通

![e5a5f87758276c1ab7fbe93593c0a03](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/78136057/5c0ed5a8-2a99-4667-a68b-ff55ce6a1757)
试了ping的通呀

**Comment by iMagist486** [comment]
那检查下查询吧，index写的对不对，有没有改动过我的插入和查询的代码

**Comment by winnie1228** [comment]
你好 昨天的问题解决了谢谢~ 但是出现新的问题，麻烦帮忙看下：
![image](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/78136057/1fb98b7a-12d9-4a16-be82-651e63639578)
我用kibana直接执行查询语句，发现返回的_source中没有metadata
![image](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/78136057/fcf69dbc-6749-4bf0-a245-006238bc0745)
请问这个问题怎么处理？

**Comment by iMagist486** [comment]
你应该没有用我的代码插入数据吧，我插入数据用的是langchain的封装，metadata写在langchian的es模块里，里面的source是用来存储文件名的

**Comment by winnie1228** [comment]
> 你应该没有用我的代码插入数据吧，我插入数据用的是langchain的封装，metadata写在langchian的es模块里，里面的source是用来存储文件名的

我是直接用你的代码启动在页面上传文件，只加了一些日志打印

**Comment by winnie1228** [comment]
还有个问题，请问我做近似查询的时候返回的content是这样，这个正常吗？
![image](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/78136057/920e348b-18c5-4709-9e5d-d0c9fe4b53fc)

**Comment by iMagist486** [comment]
不正常，你检查这些是不是存在了ES里，可能是你文档里的分割线之类的，调整分段逻辑或者写个正则过滤掉

**Comment by winnie1228** [comment]
> 不正常，你检查这些是不是存在了ES里，可能是你文档里的分割线之类的，调整分段逻辑或者写个正则过滤掉

哦哦好的 谢谢~

**Comment by MeWannaSleep** [comment]
> 你好 昨天的问题解决了谢谢~ 但是出现新的问题，麻烦帮忙看下： ![image](https://user-images.githubusercontent.com/78136057/264920687-1fb98b7a-12d9-4a16-be82-651e63639578.png) 我用kibana直接执行查询语句，发现返回的_source中没有metadata ![image](https://user-images.githubusercontent.com/78136057/264920951-fcf69dbc-6749-4bf0-a245-006238bc0745.png) 请问这个问题怎么处理？

老哥,你这个问题怎么解决的?

**Comment by MeWannaSleep** [comment]
> 你应该没有用我的代码插入数据吧，我插入数据用的是langchain的封装，metadata写在langchian的es模块里，里面的source是用来存储文件名的

作者,你好,我对你的代码没有任何修改,除了es的配置,但是还是出现了这样的错误,请问要怎么修改啊

**Comment by winnie1228** [comment]
> > 你好 昨天的问题解决了谢谢~ 但是出现新的问题，麻烦帮忙看下： ![image](https://user-images.githubusercontent.com/78136057/264920687-1fb98b7a-12d9-4a16-be82-651e63639578.png) 我用kibana直接执行查询语句，发现返回的_source中没有metadata ![image](https://user-images.githubusercontent.com/78136057/264920951-fcf69dbc-6749-4bf0-a245-006238bc0745.png) 请问这个问题怎么处理？
> 
> 老哥,你这个问题怎么解决的?

我没有真正解决，改代码不取这个属性直接规避掉了

**Comment by MeWannaSleep** [comment]
> > > 你好 昨天的问题解决了谢谢~ 但是出现新的问题，麻烦帮忙看下： ![image](https://user-images.githubusercontent.com/78136057/264920687-1fb98b7a-12d9-4a16-be82-651e63639578.png) 我用kibana直接执行查询语句，发现返回的_source中没有metadata ![image](https://user-images.githubusercontent.com/78136057/264920951-fcf69dbc-6749-4bf0-a245-006238bc0745.png) 请问这个问题怎么处理？
> > 
> > 
> > 老哥,你这个问题怎么解决的?
> 
> 我没有真正解决，改代码不取这个属性直接规避掉了

老哥,不取这个i['_source']['metadata']['source']的话,你source对应的值要怎么填,也不能直接删除啊,我看这个source在doc_format里有调用
![image](https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/135443303/0f7fdbf1-f5be-4a86-8912-102fc5081344)

**Comment by iMagist486** [comment]
> 你应该没有用我的代码插入数据吧，我插入数据用的是langchain的封装，metadata写在langchian的es模块里，里面的source是用来存储文件名的

<img width="585" alt="763263b2f0f2c2a16e73582761c23d4" src="https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/72681402/5e7483d5-62e7-47bf-ab3b-764cac8afc15">
<img width="438" alt="e788c7ab9a85bc9ac7d2e96d8487982" src="https://github.com/iMagist486/ElasticSearch-Langchain-Chatglm2/assets/72681402/fc718c19-995c-4a60-a14d-e719cde1ae73">
不理解你们为什么ES里没有metadata字段，这是langchain包里的相关代码，你们可以看一下，debug找找原因

**Comment by zhangming880102** [comment]
找到原因了，langchain0.0.266 elastic_vector_search.py里的add_texts没有把metadatas加进去。
696和700行这里改一下就可以了。

        # body = []
        body: List[Mapping[str, Any]] = []
        for text, vector, metadata in zip(texts, embeddings, metadatas):
            body.extend(
                [
                    {"index": {"_index": self.index_name}},
                    {"text": text, "vector": vector, "metadata": metadata},
                ]
            )

**Comment by MeWannaSleep** [comment]
> 找到原因了，langchain0.0.266 elastic_vector_search.py里的add_texts没有把metadatas加进去。 696和700行这里改一下就可以了。
> 
> ```
>     # body = []
>     body: List[Mapping[str, Any]] = []
>     for text, vector, metadata in zip(texts, embeddings, metadatas):
>         body.extend(
>             [
>                 {"index": {"_index": self.index_name}},
>                 {"text": text, "vector": vector, "metadata": metadata},
>             ]
>         )
> ```

牛逼老哥

**Comment by MeWannaSleep** [comment]
> 找到原因了，langchain0.0.266 elastic_vector_search.py里的add_texts没有把metadatas加进去。 696和700行这里改一下就可以了。
> 
> ```
>     # body = []
>     body: List[Mapping[str, Any]] = []
>     for text, vector, metadata in zip(texts, embeddings, metadatas):
>         body.extend(
>             [
>                 {"index": {"_index": self.index_name}},
>                 {"text": text, "vector": vector, "metadata": metadata},
>             ]
>         )
> ```

@iMagist486  老哥,可能把三方库具体版本写在requirements.txt会更好一些

**Comment by iMagist486** [comment]
> > 找到原因了，langchain0.0.266 elastic_vector_search.py里的add_texts没有把metadatas加进去。 696和700行这里改一下就可以了。
> > ```
> >     # body = []
> >     body: List[Mapping[str, Any]] = []
> >     for text, vector, metadata in zip(texts, embeddings, metadatas):
> >         body.extend(
> >             [
> >                 {"index": {"_index": self.index_name}},
> >                 {"text": text, "vector": vector, "metadata": metadata},
> >             ]
> >         )
> > ```
> 
> @iMagist486 老哥,可能把三方库具体版本写在requirements.txt会更好一些

好的， @zhangming880102 感谢分享

**Comment by v-yunbin** [comment]
> > > 找到原因了，langchain0.0.266 elastic_vector_search.py里的add_texts没有把metadatas加进去。 696和700行这里改一下就可以了。
> > > ```
> > >     # body = []
> > >     body: List[Mapping[str, Any]] = []
> > >     for text, vector, metadata in zip(texts, embeddings, metadatas):
> > >         body.extend(
> > >             [
> > >                 {"index": {"_index": self.index_name}},
> > >                 {"text": text, "vector": vector, "metadata": metadata},
> > >             ]
> > >         )
> > > ```
> > 
> > 
> > @iMagist486 老哥,可能把三方库具体版本写在requirements.txt会更好一些
> 
> 好的， @zhangming880102 感谢分享

@iMagist486 现在langchain都用到0.1.13版本了，依然langchain这个代码依然没加metadata，是这个字段不重要吗
